course_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First Loading View Webpage
    path('', views.home, name='home'),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls')),
    path('teachers/', include('teachers.urls')),
    path('user/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import CourseListView, CourseCreateView, CourseDeleteView, CourseUpdateView, CourseDetailView

app_name = 'courses'
urlpatterns = [
    path('home/', CourseListView.as_view(), name='home'),
    path('add_course/', CourseCreateView.as_view(), name='add_course'),
    path('delete_course/<int:pk>/', CourseDeleteView.as_view(), name='delete_course'),
    path('edit_course/<int:pk>/', CourseUpdateView.as_view(), name='edit_course'),
    path('view_course/<int:pk>/', CourseDetailView.as_view(), name="view_course"),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'
urlpatterns = [
  path('home/', views.home, name='home'),
  path('add_student/', views.add_student, name='add_student'),
  path('delete_student/<int:pk>/', views.delete_student, name='delete_student'),
  path('view_student/<int:pk>/', views.view_student, name='view_student'),
  path('edit_student/<int:pk>/', views.edit_student, name='edit_student'),
]

teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreateView, TeacherDetailView, TeacherDeleteView, TeacherUpdateView

app_name = 'teachers'
urlpatterns = [
    path('home/', TeacherListView.as_view(), name='home'),
    path('add_teacher/', TeacherCreateView.as_view(), name='add_teacher'),
    path('detail_teacher/<int:pk>/', TeacherDetailView.as_view(), name='detail_teacher'),
    path('delete_teacher/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
    path('edit_teacher/<int:pk>/', TeacherUpdateView.as_view(), name='edit_teacher'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('<int:pk>/logout/', views.logoutUser, name='logout'),
]

students/models.py
from django.db import models
from courses.models import Course
from teachers.models import Teacher


class Student(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField(blank=True, null=True)
    email = models.EmailField()
    gender_choice = (
        ('F', 'Female'),
        ('M', 'Male'),
        ('O', 'Other'),
    )
    gender = models.CharField(max_length=1, choices=gender_choice)
    course = models.ForeignKey(Course, on_delete=models.PROTECT, related_name='students', null=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, related_name='students', null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        db_table = 'Student'

students/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import Student
from courses.models import Course
from teachers.models import Teacher
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required
def home(request):
    if not request.session.get('user'):
        return redirect(reverse('users:login'))
    courses = Course.objects.all()
    teachers = Teacher.objects.all()

    column = request.GET.get('column')
    query = request.GET.get('query')
    if not column or column == 'all':
        students = Student.objects.all()
    elif column == 'first_name':
        students = Student.objects.filter(first_name__icontains=query)
    elif column == 'last_name':
        students = Student.objects.filter(last_name__icontains=query)
    elif column == 'age':
        students = Student.objects.filter(age=query)
    elif column == 'email':
        students = Student.objects.filter(email__icontains=query)
    elif column == 'course':
        students = Student.objects.filter(course__name__icontains=query)
    elif column == 'teacher':
        students = Student.objects.filter(teacher__first_name__icontains=query)

    return render(request, 'students/home.html', {'students': students, 'teachers': teachers, 'courses': courses})


def view_student(request, pk):
    student = Student.objects.get(pk=pk)
    if student:
        return render(request, 'students/view_student.html', {'student': student})


def add_student(request):
    if request.method == 'POST':
        error_messages = {}

        first_name = request.POST.get('first_name')
        if not first_name:
            error_messages['error_first_name'] = 'Field First Name is required!'

        last_name = request.POST.get('last_name')
        if not last_name:
            error_messages['error_last_name'] = 'Field Last Name is required!'

        age = request.POST.get('age')
        if not age:
            error_messages['error_age'] = 'Field Age is required!'

        email = request.POST.get('email')

        if email and Student.objects.filter(email=email).exists():
            error_messages['email_exists'] = "A student with the same email already exists."

        if not email:
            error_messages['email_error'] = 'Field email is required!'

        gender = request.POST.get('gender')
        if not gender:
            error_messages['gender_error'] = 'Field gender is required!'
        
        course = request.POST.get('course')
        if not course:
            error_messages['course_error'] = 'Field course is required!'

        teacher = request.POST.get('teacher')
        if not teacher:
            error_messages['teacher_error'] = 'Field teacher is required!'

        if error_messages:
            return render(request, 'students/add_student.html', error_messages)
        else:
            course_id = request.POST.get('course')
            course = Course.objects.get(pk=course_id)
            teacher_id = request.POST.get('teacher')
            teacher = Teacher.objects.get(pk=teacher_id)
            Student.objects.create(
                first_name=first_name,
                last_name=last_name,
                age=age,
                email=email,
                gender=gender,
                course=course,
                teacher=teacher
            )
            messages.success(request, 'Student added successfully!')
        return redirect('students:home')
    elif request.method == 'GET':
        return render(request, 'students/add_student.html', {'teachers': Teacher.objects.all(), 'courses': Course.objects.all()})


def delete_student(request, pk):
    if request.method == "POST":
        student = get_object_or_404(Student, pk=pk)
        student.delete()
    return HttpResponseRedirect(reverse('students:home'))


def edit_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    teachers = Teacher.objects.all()
    courses = Course.objects.all()

    if request.method == 'POST':
        student.first_name = request.POST.get('first_name')
        student.last_name = request.POST.get('last_name')
        student.age = request.POST.get('age')
        student.email = request.POST.get('email')
        student.course.pk = request.POST.get('course')
        student.course = Course.objects.get(pk=student.course.pk)

        student.save()
        return HttpResponseRedirect(reverse('students:home'))

students/templates/students/add_student.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<div>
  <i class='bx bxs-id-card h2 align-middle' ></i> Add new student
</div>
{% endblock title %}

{% block content %}
<div class="shadow border p-4 mb-5 bg-white my-4 rounded">
  <form action="{% url 'students:add_student' %}" method="POST">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-4">
        <img src="{% static 'images/user-add.png' %}" class="mx-auto d-block img-fluid w-75">
        <div class="text-center">
          <button type="submit" class="btn btn-primary m-3 w-75">Add</button>
        </div>
      </div>

      <div class="col-md-8">
        <div class="row">
          <div class="col-sm-4 form-group m-3">
            <label for="first_name">First Name</label>
            <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Your name...">
            {% if error_first_name %}
              <span style="color: red;">{{ error_first_name }}</span>
            {% endif %}
          </div>

          <div class="col-sm-4 form-group m-3">
            <label for="last_name">Last Name</label>
            <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Your lastname...">
            {% if error_last_name %}
              <span style="color: red;">{{ error_last_name }}</span>
            {% endif %}
          </div>

          <div class="col-sm-2 form-group m-3">
            <label for="age">Age</label>
            <input type="number" class="form-control" id="age" name="age">
            {% if error_age %}
              <span style="color: red;">{{ error_age }}</span>
            {% endif %}
          </div>
        </div>

        <div class="row">
          <div class="col-sm-5 form-group m-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email">
            {% if email_exists %}
              <span style="color: red;">{{ email_exists }}</span>
            {% endif %}

            {% if email_error %}
              <span style="color: red;">{{ email_error }}</span>
            {% endif %}
          </div>

          <div class="col-sm-5 form-group d-flex flex-column justify-content-center align-items-start">
            <label class="h5">Gender</label>
            <div class="d-flex align-item-center">
              <div class="form-check">
                <input class="form-check-input mx-1" type="radio" name="gender" id="male" value="M" checked>
                <label class="form-check-label" for="male">
                  Male
                </label>
              </div>
            
              <div class="form-check">
                <input class="form-check-input mx-1" type="radio" name="gender" id="female" value="F">
                <label class="form-check-label" for="female">
                Female
                </label>
              </div>

              <div class="form-check">
                <input class="form-check-input mx-1" type="radio" name="gender" id="other" value="O">
                <label class="form-check-label" for="other">
                  Other
                </label>
              </div>
              
              {% if gender_error %}
                <span style="color: red;">{{ gender_error }}</span>
              {% endif %}
              </div>
          </div>
        </div>

        <div class="row mx-2">
          <div class="col-sm-6 form-group">
            <label for="course">Course</label>
            <select class="form-control" id="course" name="course">
              <option value="">-- Select Course --</option>
              {% for course in courses %}
                <option value="{{ course.pk }}">{{ course.name }}</option>
              {% endfor %}
            </select>
            {% if course_error %}
              <span style="color: red;">{{ course_error }}</span>
            {% endif %}
          </div>

          <div class="col-sm-6 form-group">
            <label for="teacher">Teacher</label>
            <select class="form-control" id="teacher" name="teacher">
              <option value="">-- Select Teacher --</option>
              {% for teacher in teachers %}
                <option value="{{ teacher.id }}">{{ teacher.first_name }} {{ teacher.last_name }}</option>
              {% endfor %}
            </select>
            {% if teacher_error %}
              <span style="color: red;">{{ teacher_error }}</span>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}

students/templates/students/delete_student.html
{% load static %}
<div class="modal" id="deleteModal{{ student.pk }}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header p-3">
          <h5 class="modal-title">
              <p class="m-0">Are you sure you want to delete this student?</p>
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5">
                    <img src="{% static 'images/user-delete.png' %}" class="mx-auto d-block img-fluid w-75">
                </div>
                <div class="col-md-7 d-flex flex-column justify-content-center align-items-center">
                    <h4><b>Student: </b>&nbsp;</h4>
                    <h4> {{ student.first_name }} {{ student.last_name }}</h4>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <form action="{% url 'students:delete_student' student.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Delete">
          </form>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

students/templates/students/edit_student.html
{% load static %}
<div class="modal fade" id="editModal{{ student.pk }}" tabindex="-1" aria-labelledby="editStudentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="editStudentModalLabel"><i class='bx bxs-edit align-middle h1'  style='color:#5e6262'></i> Edit Student</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="editStudentForm{{student.pk}}" method="post" action="{% url 'students:edit_student' student.pk %}">
            {% csrf_token %}

              <!-- First Name & Last Name-->
              <div class="row">
                <div class="mb-3 col-md-6">
                  <label for="editFirstName" class="form-label">First Name</label>
                  <input type="text" class="form-control" id="editFirstName" name="first_name" value="{{ student.first_name }}">
                </div>
                <div class="mb-3 col-md-6">
                  <label for="editLastName" class="form-label">Last Name</label>
                  <input type="text" class="form-control" id="editLastName" name="last_name" value="{{ student.last_name }}">
                </div>
              </div>

              <!-- Age & Email -->
              <div class="row">
                <div class="mb-3 col-md-2">
                  <label for="editAge" class="form-label">Age</label>
                  <input type="number" class="form-control" id="editAge" name="age" value="{{ student.age }}">
                </div>
                <div class="mb-3 col-md-10">
                  <label for="editEmail" class="form-label">Email</label>
                  <input type="email" class="form-control" id="editEmail" name="email" value="{{ student.email }}">
                </div>
              </div>

              <!-- Course & Teacher -->
              <div class="row">
                  <div class="mb-3 col-md-6">
                      <label for="editCourse" class="form-label">Course</label>
                      <select class="form-select" id="editCourse" name="course">
                        {% for course in courses %}
                          {% if course.pk == student.course.pk %}
                            <option value="{{ course.pk }}" selected>{{ course.name }}</option>
                          {% else %}
                            <option value="{{ course.pk }}">{{ course.name }}</option>
                          {% endif %}
                        {% endfor %}
                      </select>
                  </div>
                  <div class="mb-3 col-md-6">
                      <label for="editTeachers" class="form-label">Teachers</label>
                      <select class="form-select" id="editTeachers" name="teachers">
                        {% for teacher in teachers %}
                        {% if teacher in student.teachers.all %}
                        <option value="{{ teacher.pk }}" selected>{{ teacher.first_name }} {{ teacher.last_name }}</option>
                        {% else %}
                        <option value="{{ teacher.pk }}">{{ teacher.first_name }} {{ teacher.last_name }}</option>
                        {% endif %}
                        {% endfor %}
                      </select>
                  </div>
              </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" form="editStudentForm{{student.pk}}">Save Changes</button>
        </div>
      </div>
    </div>
  </div>

students/templates/students/home.html
{% extends 'base.html' %}
{% load static %}


{% block tab_name %}
	<title>CMS | Students</title>
{% endblock tab_name %}


{% block search_input %}
<div class="input-group d-flex mt-2 justify-content-between search">
    <!-- Include template search.html for search by column in rows table -->
    {% include 'students/search.html' %}

    <div class="add-button my-1">
        <a type="submit" class="btn btn-primary mx-2" href="{% url 'students:add_student' %}">
            <div class="centered-icon">
              <i class='bx bx-plus' ></i>
              <span>Add Student</span>
            </div>
        </a>
    </div>
</div>
{% endblock search_input %}


{% block title %}
    <div><i class='bx bxs-user-detail align-middle h1' style='color:#5e6262'></i> Students </div>
{% endblock title %}


{% block content %}
{% if students %}
<table class="table table-striped tbl mt-3">
    <thead>
      <tr class="text-light" style="background-color: #414141;">
        <th scope="col">ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Course</th>
        <th scope="col">Teacher</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        {% for student in students %}
      <tr>
        <th scope="row">{{ student.pk }}</th>
        <td>{{ student.first_name }}</td>
        <td>{{ student.last_name }}</td>
        <td>{{ student.email }}</td>
        <td>
           <a href="{% url 'courses:home' %}#{{student.course.pk}}" style="text-decoration: none; color: #1A2980;">
                {{ student.course }}
            </a>
        </td>
        <td>
            <a href="{% url 'teachers:home' %}#{{student.teacher.pk}}" style="text-decoration: none; color: #1A2980;">
                {{ student.teacher }}
            </a>
        </td>
        <td>

          <!-- Links for CRUD -->
          <a href="{% url 'students:view_student' student.pk %}" data-bs-toggle="modal" data-bs-target="#viewModal{{ student.pk }}"><i class='bx bxs-info-square' style='color:#83b5e5'  ></i></a>
          <a href="{% url 'students:edit_student' student.pk %}" data-bs-toggle="modal" data-bs-target="#editModal{{ student.pk }}"><i class='bx bxs-edit' style='color:#b6c80a'  ></i></a>
          <a href="{% url 'students:delete_student' student.pk %}" data-bs-toggle="modal" data-bs-target="#deleteModal{{ student.pk }}"><i class='bx bx-trash' style='color:#df243d'  ></i></a>

          <!-- Modal - View Student -->
            {% include 'students/view_student.html' %}
          <!-- End Student View Modal -->

          <!-- Modal - Edit Student -->
            {% include 'students/edit_student.html' %}
          <!-- End Modal - Edit Student -->

          <!-- Modal - Delete Student -->
            {% include 'students/delete_student.html' %}
          <!-- End Modal - Delete Student -->
        </td>
      </tr>
      {% endfor %}
    </tbody>
</table>
  {% else %}
    <h5 class="alert alert-light ms-4 me-4">No Students Records</h5>
    {% endif %}
{% endblock content %}

students/templates/students/search.html
<form method="GET" action="{% url 'students:home' %}" class="w-75">
    <div class="input-group my-1 justify-content-center align-items-center">
        <span class="d-flex align-items-center mx-2 my-0 h5 text-secondary">Search by: </span>
        <select name="column" class="form-select">
            <option value="all" selected>All</option>
            <option value="first_name">First Name</option>
            <option value="last_name">Last Name</option>
            <option value="email">Email</option>
            <option value="course">Course</option>
            <option value="teacher">Teacher</option>
        </select>
        <input type="text" name="query" class="form-control w-25" placeholder="Search">
           <button type="submit" class="btn btn-primary ">
                <i class="fas fa-search"></i>
           </button>
    </div>
</form>

students/templates/students/view_student.html
{% load static %}
<div class="modal" id="viewModal{{ student.pk }}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <i class='bx bxs-info-circle align-middle h1' style='color:#5ca2ff'  ></i> Student: {{ student.first_name }} {{ student.last_name }}
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-5">
                    <img src="{% static 'images/user-info.png'  %}" class="img-fluid">
                </div>
                <div class="col-md-7 d-flex align-items-center">
                    <ul class="list-unstyled">
                    <li>Student Number: <strong>{{ student.pk }}</strong></li>
                    <li>First Name: <strong>{{ student.first_name }}</strong></li>
                    <li>Last Name: <strong>{{ student.last_name }}</strong></li>
                    <li>Age: <strong>{{ student.age }}</strong></li>
                    <li>Email: <strong>{{ student.email}}</strong></li>
                    <li>Gender: <strong>{{ student.get_gender_display }}</strong></li>
                    <li>Course: <strong>{{ student.course }}</strong></li>
                    <li>Teacher: <strong>{{ student.teacher }}</strong></li>
                  </ul>
                </div>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>