course_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First Loading View Webpage
    path('', views.home, name='home'),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls')),
    path('teachers/', include('teachers.urls')),
    path('user/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreateView, TeacherDetailView, TeacherDeleteView, TeacherUpdateView

app_name = 'teachers'
urlpatterns = [
    path('home/', TeacherListView.as_view(), name='home'),
    path('add_teacher/', TeacherCreateView.as_view(), name='add_teacher'),
    path('detail_teacher/<int:pk>/', TeacherDetailView.as_view(), name='detail_teacher'),
    path('delete_teacher/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
    path('edit_teacher/<int:pk>/', TeacherUpdateView.as_view(), name='edit_teacher'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('<int:pk>/logout/', views.logoutUser, name='logout'),
]

teachers/models.py
from django.db import models
from courses.models import Course


class Teacher(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    age = models.IntegerField()
    email = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='teacher')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def num_students(self):
        return self.course.students.count()

    class Meta:
        db_table = 'Teacher'

teachers/forms.py
from django import forms
from .models import Teacher


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'age', 'email', 'course']
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'age': 'Age',
            'email': 'Email',
            'course': 'Course'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your name...'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your name...'}),
            'age': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Your age...'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Your email...'}),
            'course': forms.Select(attrs={'class': 'form-control'}),
        }

teachers/views.py
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from .forms import TeacherForm
from .models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers/home.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('user'):
            return redirect(reverse('users:login'))
        return super().dispatch(request, *args, **kwargs)


class TeacherCreateView(CreateView):
    model = Teacher
    form_class = TeacherForm
    template_name = 'teachers/add_teacher.html'
    success_url = reverse_lazy('teachers:home')


class TeacherDetailView(DetailView):
    model = Teacher
    template_name = "detail_teacher.html"


class TeacherDeleteView(DeleteView):
    model = Teacher
    template_name = 'detail_teacher.html'
    success_url = reverse_lazy("teachers:home")


class TeacherUpdateView(UpdateView):
    model = Teacher
    form_class = TeacherForm
    template_name = 'teachers/edit_teacher.html'
    success_url = reverse_lazy('teachers:home')

teachers/templates/teachers/add_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<div>
  <i class='bx bxs-id-card h2 align-middle' ></i> Add new course
</div>
{% endblock title %}

{% block content %}
  <div class="shadow border p-4 mb-5 bg-white my-4 rounded">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="row">
        <div class="col-md-5">
          <img src="{% static 'images/teachers.png' %}" class="mx-auto d-block img-fluid w-75">
          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary m-3 w-75">Add</button>
          </div>
        </div>
        
        <div class="col-md-7">
          <!-- {{ form.as_p }} -->
          <div class="row mt-2 mb-3">
            <div class="col-md-6">
              {{ form.first_name.label }}
              {{ form.first_name }}
            </div>
            <div class="col-md-6">
              {{ form.last_name.label }}
              {{ form.last_name }}
            </div>
          </div>
          <div class="row my-3">
            <div class="col-md-6">
              {{ form.age.label }}
              {{ form.age }}
            </div>
            <div class="col-md-6">
              {{ form.email.label }}
              {{ form.email }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {{ form.course.label }}
              {{ form.course }}
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

teachers/templates/teachers/detail_teacher.html
{% load static %}
<div class="modal" id="viewModal{{ teacher.pk }}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <i class='bx bxs-info-circle align-middle h1' style='color:#5ca2ff'  ></i> Teacher:
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{% static 'images/user-info.png' %}" class="img-fluid mx-auto" >
                </div>
                <div class="col-md-8 d-flex justify-content-center align-items-center">
                  <ul class="list-unstyled m-0">
                    <li>First Name: <strong>{{ teacher.first_name }}</strong></li>
                    <li>Last Name: <strong>{{ teacher.last_name }}</strong></li>
                    <li>Age: <strong>{{ teacher.age }}€</strong></li>
                    <li>Email: <strong>{{ teacher.email }}</strong></li>
                    <li>Course: <strong>{{ teacher.course }}</strong></li>
                    <li>Students nr: <strong>{{ teacher.num_students }}</strong></li>
                  </ul>
                </div>
            </div>

        </div>
        <div class="modal-footer">
          <form action="{% url 'teachers:delete_teacher' teacher.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
          </form>
          <a href="{% url 'teachers:edit_teacher' teacher.pk %}" class="btn btn-warning">Edit</a>
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

teachers/templates/teachers/edit_teacher.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<div>
  <i class='bx bxs-id-card h2 align-middle' ></i> Edit Teacher
</div>
{% endblock title %}

{% block content %}
  <div class="shadow border p-4 mb-5 bg-white my-4 rounded">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="row">
        <div class="col-md-5">
          <img src="{% static 'images/teacher.png' %}" class="mx-auto d-block img-fluid w-75">
          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary m-3 w-75">Edit</button>
          </div>
        </div>

        <div class="col-md-7">
          <!-- {{ form.as_p }} -->
          <div class="row mt-2 mb-3">
            <div class="col-md-6">
              {{ form.first_name.label }}
              {{ form.first_name }}
            </div>
            <div class="col-md-6">
              {{ form.last_name.label }}
              {{ form.last_name }}
            </div>
          </div>
          <div class="row my-3">
            <div class="col-md-6">
              {{ form.age.label }}
              {{ form.age }}
            </div>
            <div class="col-md-6">
              {{ form.email.label }}
              {{ form.email }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {{ form.course.label }}
              {{ form.course }}
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

teachers/templates/teachers/home.html
{% extends 'base.html' %}
{% load static %}
{% block tab_name %}
	<title>CMS | Teachers</title>
{% endblock tab_name %}


{% block search_input %}
<div class="input-group d-flex mt-2 justify-content-end">
    <div class="add-button my-1">
        <a type="submit" class="btn btn-primary mx-2" href="{% url 'teachers:add_teacher' %}">
            <div class="centered-icon">
              <i class='bx bx-plus' ></i>
              <span>Add Teacher</span>
            </div>
        </a>
    </div>
</div>
{% endblock search_input %}

{% block title %}
        <div><i class='bx bxs-user-badge align-middle h2' style='color:#5e6262'></i> Teachers </div>
{% endblock title %}


{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4 my-2">
{% for teacher in teacher_list %}
<div class="col-md-4 teacher-cards hover-shadow" id="{{ teacher.pk }}">
    <a href="" class="card-link text-decoration-none text-dark" data-bs-toggle="modal" data-bs-target="#viewModal{{ teacher.pk }}">
    <div class="card shadow">
        <div class="card-content">
        <div class="card-body">
            <div class="media d-flex">
            <div class="media-body text-left col-7">
                <h3 class="text-success mb-3">{{ teacher.num_students }} <span class="h6">Students</span></h3>
                <span>{{ teacher }}</span><br>
                <span style="font-size: 12px;" class="text-success">Course: </span>
                <span style="font-size: 12px;color: #167CCA;">{{ teacher.course }}</span>
            </div>
            <div class="align-self-center col-5">
                <img src="{% static 'images/teacher.png' %}" class="mx-auto d-block img-fluid w-75">
            </div>
            </div>
        </div>
        </div>
    </div>
</a>
</div>
    <!-- Calling Modal Bootstrap saved on view_course.html -->
    {% include 'teachers/detail_teacher.html' %}
{% endfor %}
</div>
{% endblock content %}