course_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First Loading View Webpage
    path('', views.home, name='home'),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls')),
    path('teachers/', include('teachers.urls')),
    path('user/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import CourseListView, CourseCreateView, CourseDeleteView, CourseUpdateView, CourseDetailView

app_name = 'courses'
urlpatterns = [
    path('home/', CourseListView.as_view(), name='home'),
    path('add_course/', CourseCreateView.as_view(), name='add_course'),
    path('delete_course/<int:pk>/', CourseDeleteView.as_view(), name='delete_course'),
    path('edit_course/<int:pk>/', CourseUpdateView.as_view(), name='edit_course'),
    path('view_course/<int:pk>/', CourseDetailView.as_view(), name="view_course"),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('<int:pk>/logout/', views.logoutUser, name='logout'),
]

courses/models.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='courses')
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Course'

courses/forms.py
from django import forms
from .models import Course


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'price', 'image', 'start_date', 'notes']
        labels = {
            'name': 'Name',
            'price': 'Price',
            'image': 'Image',
            'notes': 'Notes',
            'start_date': 'Start Date'
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your name...'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Course price...'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'start_date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'class': 'form-control', 'cols': 5, 'rows': 5, 'placeholder': 'Description for course...'}),
        }

courses/views.py
from django.db.models import ProtectedError
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy, reverse

from .models import Course
from .forms import CourseForm


class CourseListView(ListView):
    model = Course
    template_name = 'courses/home.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.session.get('user'):
            return redirect(reverse('users:login'))
        return super().dispatch(request, *args, **kwargs)


class CourseCreateView(CreateView):
    model = Course
    form_class = CourseForm
    template_name = 'courses/add_course.html'
    success_url = reverse_lazy('courses:home')


class CourseDetailView(DetailView):
    model = Course
    template_name = "courses/view_course.html"


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseForm
    template_name = 'courses/edit_course.html'
    success_url = reverse_lazy('courses:home')
    

class CourseDeleteView(DeleteView):
    model = Course
    template_name = 'courses/delete_course.html'
    success_url = reverse_lazy("courses:home")

courses/templates/courses/add_course.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<div>
  <i class='bx bxs-id-card h2 align-middle' ></i> Add new course
</div>
{% endblock title %}

{% block content %}
  <div class="shadow border p-4 mb-5 bg-white my-4 rounded">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="row">
        <div class="col-md-5">
          <img src="{% static 'images/course.png' %}" class="mx-auto d-block img-fluid w-75">
          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary m-3 w-75">Add</button>
          </div>
        </div>
        
        <div class="col-md-7">
          <!-- {{ form.as_p }} -->
          <div class="row mt-2 mb-3">
            <div class="col-md-6">
              {{ form.name.label }}
              {{ form.name }}
            </div>
            <div class="col-md-6">
              {{ form.price.label }}
              {{ form.price }}
            </div>
          </div>
          <div class="row my-3">
            <div class="col-md-6">
              {{ form.image.label }}
              {{ form.image }}
            </div>
            <div class="col-md-6">
              {{ form.start_date.label }}
              {{ form.start_date }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {{ form.notes.label }}
              {{ form.notes }}
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

courses/templates/courses/delete_course.html
<div class="modal" id="deleteModal{{ course.pk }}" tabindex="-1" aria-labelledby="myModalLabel2" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header p-3">
          <h5 class="modal-title">
              <p class="m-0">Are you sure you want to delete this course?</p>
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ course.image.url }}" class="img-fluid w-75">
                </div>
                <div class="col-md-8 d-flex align-items-center">
                    <h4><b>Course: </b>&nbsp;</h4>
                    <h4> {{ course.name }}</h4>
                </div>
                  <p class="text-danger fs-6 mt-4">Note: If you click delete, the course will be deleted!</p>
            </div>
        </div>
        <div class="modal-footer">
          <form action="{% url 'courses:delete_course' course.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Delete">
          </form>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

courses/templates/courses/edit_course.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<div>
  <i class='bx bxs-id-card h2 align-middle' ></i> Edit Course
</div>
{% endblock title %}

{% block content %}
  <div class="shadow border p-4 mb-5 bg-white my-4 rounded">
    <form method="post" action="" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="row">
        <div class="col-md-5">
          <img src="{% static 'images/edit-course.png' %}" class="mx-auto d-block img-fluid w-75">
          <div class="text-center mt-3">
            <button type="submit" class="btn btn-primary m-3 w-75">Edit</button>
          </div>
        </div>

        <div class="col-md-7">
          <!-- {{ form.as_p }} -->
          <div class="row mt-2 mb-3">
            <div class="col-md-6">
              {{ form.name.label }}
              {{ form.name }}
            </div>
            <div class="col-md-6">
              {{ form.price.label }}
              {{ form.price }}
            </div>
          </div>
          <div class="row my-3">
            <div class="col-md-6">
              {{ form.image.label }}
              {{ form.image }}
            </div>
            <div class="col-md-6">
              {{ form.start_date.label }}
              {{ form.start_date }}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {{ form.notes.label }}
              {{ form.notes }}
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

courses/templates/courses/home.html
{% extends 'base.html' %}
{% load static %}
{% block tab_name %}
	<title>CMS | Courses</title>
{% endblock tab_name %}

{% block search_input %}
<div class="input-group d-flex mt-2 justify-content-end">
    <div class="add-button my-1">
        <a type="submit" class="btn btn-primary mx-2" href="{% url 'courses:add_course' %}">
            <div class="centered-icon">
              <i class='bx bx-plus' ></i>
              <span>Add Course</span>
            </div>
        </a>
    </div>
</div>
{% endblock search_input %}


    {% block title %}
        <div><i class='bx bxs-book-content align-middle h2' style='color:#5e6262'></i> Courses</div>
    {% endblock title %}

{% block content %}
<div class="row row-cols-1 row-cols-md-3 g-4 my-2">
    {% for course in course_list %}
    <div class="col" id="{{ course.pk }}">
      <div class="card h-100 shadow">
        <img src="{{ course.image.url }}" class="card-img-top" alt="{{ course.name }}">
        <div class="card-header d-flex justify-content-between p-2">
          {{ course.name }}<p class="h6 d-flex align-items-center justify-content-end text-primary m-0"><i class='bx bx-euro'></i>{{ course.price }}</p>
        </div>
        <div class="card-body">
          <p class="card-text">{{ course.notes }}</p>
        </div>
        <div class="card-footer d-flex justify-content-between p-2">
            <small class="text-muted">Posted: {{ course.created_at|date:"Y-m-d" }}</small>
            <div>
              <!-- Calling Modal Bootstrap saved on view_course.html -->
              <a href="{% url 'courses:view_course' course.pk %}" data-bs-toggle="modal" data-bs-target="#viewCourseModal{{ course.pk }}"><i class='bx bxs-info-square' style='color:#83b5e5'></i></a>
              {% include 'courses/view_course.html' %}

              <!-- Calling Modal Bootstrap saved on edit_course.html -->
              <a href="{% url 'courses:edit_course' course.pk %}"><i class='bx bxs-edit' style='color:#b6c80a'></i></a>

              <!-- Calling Modal Bootstrap saved on delete_course.html -->
              <a href="{% url 'courses:delete_course' course.pk %}" data-bs-toggle="modal" data-bs-target="#deleteModal{{ course.pk }}"><i class='bx bx-trash' style='color:#df243d'></i></a>
              {% include 'courses/delete_course.html' %}

            </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}



  

courses/templates/courses/view_course.html
{% load static %}

<div class="modal" id="viewCourseModal{{ course.pk }}" tabindex="-1" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">
            <i class='bx bxs-info-circle align-middle h1' style='color:#5ca2ff'  ></i> Course:
          </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true"></span>
          </button>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{% static 'images/info-course.png' %}" class="img-fluid mx-auto" >
                </div>
                <div class="col-md-8 d-flex justify-content-center align-items-center">
                  <ul class="list-unstyled m-0">
                    <li>Name: <strong>{{ course.name }}</strong></li>
                    <li>Start Date: <strong>{{ course.start_date }}</strong></li>
                    <li>Price: <strong>{{ course.price }}€</strong></li>
                    <li>Created At: <strong>{{ course.created_at }}</strong></li>
                    <li>Updated At: <strong>{{ course.updated_at }}</strong></li>
                  </ul>
                </div>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>