course_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First Loading View Webpage
    path('', views.home, name='home'),
    path('students/', include('students.urls')),
    path('courses/', include('courses.urls')),
    path('teachers/', include('teachers.urls')),
    path('user/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from .views import CourseListView, CourseCreateView, CourseDeleteView, CourseUpdateView, CourseDetailView

app_name = 'courses'
urlpatterns = [
    path('home/', CourseListView.as_view(), name='home'),
    path('add_course/', CourseCreateView.as_view(), name='add_course'),
    path('delete_course/<int:pk>/', CourseDeleteView.as_view(), name='delete_course'),
    path('edit_course/<int:pk>/', CourseUpdateView.as_view(), name='edit_course'),
    path('view_course/<int:pk>/', CourseDetailView.as_view(), name="view_course"),
]

students/urls.py
from django.urls import path
from . import views


app_name = 'students'
urlpatterns = [
  path('home/', views.home, name='home'),
  path('add_student/', views.add_student, name='add_student'),
  path('delete_student/<int:pk>/', views.delete_student, name='delete_student'),
  path('view_student/<int:pk>/', views.view_student, name='view_student'),
  path('edit_student/<int:pk>/', views.edit_student, name='edit_student'),
]

teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreateView, TeacherDetailView, TeacherDeleteView, TeacherUpdateView

app_name = 'teachers'
urlpatterns = [
    path('home/', TeacherListView.as_view(), name='home'),
    path('add_teacher/', TeacherCreateView.as_view(), name='add_teacher'),
    path('detail_teacher/<int:pk>/', TeacherDetailView.as_view(), name='detail_teacher'),
    path('delete_teacher/<int:pk>/', TeacherDeleteView.as_view(), name='delete_teacher'),
    path('edit_teacher/<int:pk>/', TeacherUpdateView.as_view(), name='edit_teacher'),
]

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('<int:pk>/logout/', views.logoutUser, name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
    {% block tab_name %}
	<title>Course Management System</title>
    {% endblock tab_name %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
</head>
<body>

    <div class="wrapper">
        <div class="sidebar">
            <h2><a href="{% url 'home' %}">
                <img src="{% static 'images/app-logo.png' %}" class="w-50 mt-4"></a>
            </h2>
            <ul>
                <li><a href="{% url 'students:home' %}"><i class='bx bxs-group' style='color:#e9e9e9'></i> Students</a></li>
                <li><a href="{% url 'teachers:home' %}"><i class='bx bxs-user' style='color:#e9e9e9'></i> Teacher</a></li>
                <li><a href="{% url 'courses:home' %}"><i class='bx bxs-category' style='color:#e9e9e9'></i> Courses</a></li>
            </ul>
            {% if request.session.user %}
                <div class="auth-links p-0">
                   <p><a href="{% url 'users:logout' request.session.user.pk %}" class="text-decoration-none text-light">
                       Logout <i class='bx bx-log-out align-middle' style='color:#e9e9e9'></i>
                   </a></p>
                </div>
            {% else %}
               <div class="auth-links">
                   <a href="{% url 'users:login' %}" class="text-decoration-none text-light" style='color:#e9e9e9'>Login <i class='bx bx-log-in align-middle'></i></a>
               </div>
            {% endif %}
        </div>

        <div class="main_content">
            <div class="header">
            {% block title %}
                <div><i class='bx bxs-school h1 align-middle' style='color:#5e6262'></i> Welcome to our school</div>
            {% endblock title %}

                {% if request.session.user %}
                <div class="d-flex">
                    <p>
                        <a href="" class="text-decoration-none h5" style="color: #009FBD;">{{ request.session.user.username }}
                        <img src="{% static 'images/loged_in_user.png' %}" class="w-25"></a>
                    </p>
                </div>
                {% endif %}
            </div>


            {% block search_input %}
            {% endblock search_input %}

            {% block content %}
            <div class="info container">
                <div class="row">
                    <div class="col-md-6" style="text-align: justify; text-justify: inter-word;">
                        <p>This programming course is designed to take you from a beginner level to an expert
                        in a few weeks. Our experienced and knowledgeable teachers are passionate about
                        programming and will provide you with a deep understanding of programming concepts.
                        You will learn different programming languages and frameworks, as well as best
                        practices for coding. The course includes a mix of theory and hands-on practice,
                        with real-world projects that will help you build your skills and apply what you've
                        learned. We provide a supportive and collaborative environment to ensure your success,
                         with plenty of opportunities for discussion and feedback. By the end of the course,
                         you'll be able to confidently develop and deploy software applications on your own.
                         Join us today to start your journey towards becoming a programming expert!</p>
                    </div>

                    <div class="col-md-6">
                        <img src="{% static 'images/coding.webp'  %}" class="img-fluid">
                    </div>
                </div>
            </div>
            {% endblock content %}
        </div>
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>